services:
  - type: web
    name: fastapi-app
    runtime: python
    region: oregon  # or change to your preferred Render region
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
